### ISSUE TITLE
应用时报错OCI runtime create failed

### ISSUE THREAD

**Issue by rhkjyn** [crazytaxii/lxcfs-hostpath-injector#1]
按示例操作，报以下错误，敬请问怎么解？谢谢 
docker: 18.09.8   k8s: 1.14.8
kubectl describe po web-7c8497b7dd-48bhn
Events:
  Type     Reason     Age                From                   Message
  ----     ------     ----               ----                   -------
  Normal   Scheduled  14s                default-scheduler      Successfully assigned default/web-7c8497b7dd-48bhn to 172.18.69.77
  Warning  Failed     11s                kubelet, 172.18.69.77  Error: failed to start container "web": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/lxcfs/proc/swaps\\\" to rootfs \\\"/var/lib/docker/overlay2/9101fdc4ec9eb0c893fa39d5a9138c4a0770d3600bf840fcdd7b725f329e5dc2/merged\\\" at \\\"/var/lib/docker/overlay2/9101fdc4ec9eb0c893fa39d5a9138c4a0770d3600bf840fcdd7b725f329e5dc2/merged/proc/swaps\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Normal   Pulling    10s (x2 over 13s)  kubelet, 172.18.69.77  Pulling image "httpd:2.4.32"
  Normal   Pulled     8s (x2 over 11s)   kubelet, 172.18.69.77  Successfully pulled image "httpd:2.4.32"
  Normal   Created    8s (x2 over 11s)   kubelet, 172.18.69.77  Created container web
  Warning  Failed     8s                 kubelet, 172.18.69.77  Error: failed to start container "web": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/lxcfs/proc/cpuinfo\\\" to rootfs \\\"/var/lib/docker/overlay2/d74b06f899fd258e3825e209cea144a0febaa913f3e2de0d7f4cf9bda71814d0/merged\\\" at \\\"/var/lib/docker/overlay2/d74b06f899fd258e3825e209cea144a0febaa913f3e2de0d7f4cf9bda71814d0/merged/proc/cpuinfo\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by crazytaxii** [comment]
有部署好 lxcfs 守护进程吗？

**Comment by rhkjyn** [comment]
OK,搞定了，是lxcfs没起
